version: "3.9"

services:
  nats:
    image: nats:2.10-alpine
    command: ["-js", "-sd", "/data", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data

  api:
    build: ./services/api
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - NATS_URL=nats://nats:4222
      - API_PORT=8080
      - CORS_ORIGINS=http://localhost:5173
    depends_on:
      - nats

  worker:
    build: ./services/worker
    env_file:
      - ./.env
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

  web:
    build: ./services/web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8080
    depends_on:
      - api

volumes:
  nats-data: {}
